/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c WorkareaInterface -p workareainterface.h:workareainterface.cpp ../org.opentoolsandspace.WorkareaManager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "workareainterface.h"

/*
 * Implementation of interface class WorkareaInterface
 */

WorkareaInterface::WorkareaInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

WorkareaInterface::~WorkareaInterface()
{
}

