// import QtQuick 1.0 // to target S60 5th Edition or Maemo 5
import QtQuick 1.1

ListModel {
    ListElement{
        name:"Oxygen"
        icons:[
            ListElement{
                AddWidget:"list-add"
                PauseActivity:"media-playback-pause"
                CloneActivity:"tab-duplicate"
                DeleteActivity:"edit-delete"
                RunActivity:"media-playback-start"
                DialogImportant:"emblem-important"
                DialogInformation:"dialog-information"
                DialogAccept:"dialog-ok-apply"
                DialogCancel:"dialog-cancel"
                AddValue:"media-seek-forward"
                MinusValue:"media-seek-backward"
                //AddValue:"list-add"
                //MinusValue:"list-remove"
                Previous:"go-previous"
                Next:"go-next"
                Exit:"dialog-close"
                HelpTour:"help-contents"
                Bugs:"help-hint"
            }
        ]
    }
    ListElement{
        name:"Rosa"
        icons:[
            ListElement{
                AddWidget:"list-add"
                PauseActivity:"media-playback-pause"
                CloneActivity:"tab-duplicate"
                DeleteActivity:"edit-delete"
                RunActivity:"media-playback-start"
                DialogImportant:"emblem-important"
                DialogInformation:"dialog-information"
                DialogAccept:"dialog-ok-apply"
                DialogCancel:"editdelete"
                AddValue:"media-seek-forward"
                MinusValue:"media-seek-backward"
                //ddValue:"list-add"
                //MinusValue:"kt-remove"
                Previous:"go-previous"
                Next:"go-next"
                Exit:"dialog-close"
                HelpTour:"help-contents"
                Bugs:"help-hint"
            }


        ]
    }
    ListElement{
        name:"KFaenza"
        icons:[
            ListElement{
                AddWidget:"document-new"
                PauseActivity:"media-playback-pause"
                CloneActivity:"edit-copy"
                DeleteActivity:"application-exit"
                RunActivity:"media-playback-start"
                DialogImportant:"emblem-important"
                DialogInformation:"dialog-information"
                DialogAccept:"dialog-ok-apply"
                DialogCancel:"dialog-cancel"
                AddValue:"media-seek-forward"
                MinusValue:"media-seek-backward"
                Previous:"go-previous"
                Next:"go-next"
                Exit:"dialog-close"
                HelpTour:"help-contents"
                Bugs:"help-hint"
            }
        ]
    }

}
